### ISSUE TITLE
Windows Compilation Error

### ISSUE THREAD

**Issue by TheAndreiM** [darrengarvey/cgi#12]
Whenever I try to compile fcgi_hello_world on windows on Microsoft Visual Studios 2015 with boost libraries 1.59, I get the following error:

Severity    Code    Description Project File    Line
Warning C4005   'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT': macro redefinition    fcgi_hello_world    c:\boost_1_59_0\boost\asio\detail\config.hpp    227
Error   C2039   'next_layer': is not a member of 'boost::cgi::common::basic_connectionboost::cgi::common::tags::fcgi_transport'   fcgi_hello_world    c:\boost_1_59_0\boost\cgi\impl\fcgi_request_service.ipp 726
Error   C2780   'size_t boost::asio::write(SyncWriteStream &,boost::asio::basic_streambuf<Allocator> &)': expects 2 arguments - 3 provided  fcgi_hello_world    c:\boost_1_59_0\boost\cgi\impl\fcgi_request_service.ipp 726
Error   C2780   'size_t boost::asio::write(SyncWriteStream &,boost::asio::basic_streambuf<Allocator> &,CompletionCondition,boost::system::error_code &)': expects 4 arguments - 3 provided  fcgi_hello_world    c:\boost_1_59_0\boost\cgi\impl\fcgi_request_service.ipp 726
Error   C2780   'size_t boost::asio::write(SyncWriteStream &,const ConstBufferSequence &)': expects 2 arguments - 3 provided    fcgi_hello_world    c:\boost_1_59_0\boost\cgi\impl\fcgi_request_service.ipp 726
Error   C2780   'size_t boost::asio::write(SyncWriteStream &,const ConstBufferSequence &,CompletionCondition,boost::system::error_code &)': expects 4 arguments - 3 provided    fcgi_hello_world    c:\boost_1_59_0\boost\cgi\impl\fcgi_request_service.ipp 726

**Comment by TheAndreiM** [comment]
Line 507 in win32_acceptor_service_impl.hpp (acceptor_service_.accept(impl.acceptor_, *new_request->client().connection()->socket_, &impl.endpoint_, ec);)  errors out. I commented this line to get the error stated above.

**Comment by aldot** [comment]
i fixed some of those some time ago for linux FYI:
https://github.com/darrengarvey/cgi/commit/6b28a0e563c21e090a2e9f712ace384d0c770e6e
HTH

**Comment by darrengarvey** [comment]
Yep, thanks @aldot.

**Comment by aldot** [comment]
I only fixed it for linux, not for windows (can't test that).
You probably have to switch your windows impl to use next_layer(), too. Maybe something like the attached?
[win32_acceptor_service_impl-use-next_layer.00.patch.txt](https://github.com/darrengarvey/cgi/files/3074234/win32_acceptor_service_impl-use-next_layer.00.patch.txt)
